门诊管理系统/门诊管理系统/Areas/Admin/Controllers/patientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using IDAL;
using OutDepModel;
using OutDepViewModel;

namespace 门诊管理系统.Areas.Admin.Controllers
{
    public class patientController : Controller
    {
        public IOutDepadminManage dAL { get; set; }
        public IPatientmanege patientmanege { get; set; }
        public static readonly log4net.ILog log = log4net.LogManager.GetLogger("");
        public IMapper mapper = Automapper.Configmapper();
        // GET: patient
        //主页
        public ActionResult Index(string name)
        {
            if (name == null) name = "";
            var list = patientmanege.Select().Where(p => p.Name.Contains(name)).Select(p => mapper.Map<patientselectModel>(p)).ToList();
            log.Info("用户查询了该列表");

            return View(list);
        }

        private void DropList()
        {
            var models = dAL.Select();
            List<SelectListItem> selects = new List<SelectListItem>();
            foreach (var model in models)
            {
                selects.Add(new SelectListItem() { Text = model.Name, Value = model.Name });
            }
            ViewData["OutDepName"] = selects;
        }

        public ActionResult Index2(string name)
        {
            if (name == null) name = "";
            var list = patientmanege.Select().Where(p => p.Name.Contains(name)).Select(p => mapper.Map<patientselectModel>(p)).ToList();
            log.Info("用户查询了该列表");
            return View(list);
        }
        //添加显示
        public ActionResult Create()
        {
            DropList();
            return View();
        }
        //执行添加
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(patientCreateModel model, string cmbProvince, string cmbCity, string cmbArea)
        {
            try
            {
                model.Address = cmbProvince + cmbCity + cmbArea;
                var insert = mapper.Map<Patient>(model);

                patientmanege.Insert(insert);
            }
            catch (Exception ex)
            {

                log.Error(ex.Message);
            }


            return RedirectToAction("Index");
        }
        //修改显示
        public ActionResult Edit(int? Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Edit");
            }
            var temp = patientmanege.First(Id.Value);
            if (temp == null)
            {
                return RedirectToAction("Edit");
            }
            DropList();
            return View(mapper.Map<patientEditModel>(temp));
        }
        /// <summary>
        /// 执行修改
        /// </summary>
        /// <param name="moodel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]


        public ActionResult Edit(patientCreateModel moodel)
        {
            try
            {
                var Update = mapper.Map<Patient>(moodel);

                patientmanege.Update(Update);

            }
            catch (Exception ex)
            {


                log.Error(ex.Message);
            }
            return RedirectToAction("Edit");
        }

        [HttpPost]

        /// <summary>
        /// 伪删除
        /// </summary>
        /// <param name="OutDep"></param>
        /// <returns></returns>
        public ActionResult Delete(patientCreateModel OutDep)
        {
            var delete = mapper.Map<Patient>(OutDep);
            var data = patientmanege.Dleate(delete);
            return Json(data);

        }

        [HttpPost]
        public ActionResult Address()
        {
            return Json(patientmanege.Select().Select(p => p.Address));
        }
    }
}

门诊管理系统/门诊管理系统/Areas/Admin/Controllers/presciptController.cs
using AutoMapper;
using IDAL;
using OutDepModel;
using OutDepViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace 门诊管理系统.Areas.Admin.Controllers
{
    public class presciptController : Controller
    {
        public IPrescriptManage prescriptManage { get; set; }
        public static readonly log4net.ILog log = log4net.LogManager.GetLogger("");
        public IMapper mapper = Automapper.Configmapper();
        // GET: prescipt
        //主页
        public ActionResult Index()
        {
            var list = prescriptManage.Select().Select(p => mapper.Map<perscriptionSelectModel>(p)).ToList();
            log.Info("用户查询了该列表");
            return View(list);
        }
        //添加显示
        public ActionResult Create()
        {
            return View();
        }
        //执行添加
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(perscriptionCreateModel model)
        {
            try
            {
                var insert = mapper.Map<Prescription>(model);

                prescriptManage.Insert(insert);
            }
            catch (Exception ex)
            {

                log.Error(ex.Message);
            }

           
            return RedirectToAction("Index");
        }
        //修改显示
        public ActionResult Edit(int? Id)
        {
            if (Id == null)
            {
                return RedirectToAction("Edit");
            }
            var temp = prescriptManage.First(Id.Value);
            if (temp == null)
            {
                return RedirectToAction("Edit");
            }
            return View(mapper.Map<perscriptionEditModel>(temp));
        }
        /// <summary>
        /// 执行修改
        /// </summary>
        /// <param name="moodel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(perscriptionCreateModel moodel)
        {
            try
            {
                var Update = mapper.Map<Prescription>(moodel);

                prescriptManage.Update(Update);
            }
            catch (Exception ex)
            {

                log.Error(ex.Message);
            }
            
            return RedirectToAction("Edit");
        }

        [HttpPost]
        /// <summary>
        /// 伪删除
        /// </summary>
        /// <param name="OutDep"></param>
        /// <returns></returns>
        public ActionResult Delete(perscriptionCreateModel OutDep)
        {
            var delete = mapper.Map<Prescription>(OutDep);
            var data = prescriptManage.Dleate(delete);
            return Json(data);
        }
    }
}

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Root.cshtml";
}

@section styles{
    @RenderSection("styles", required: false)
}

@Html.Partial("_LeftMenu")
<div class="content-wrapper">
    <div class="container-fluid">
        @RenderBody()
    </div>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        经开人民医院门诊部
    </div>
    <strong>Copyright &copy; 2014-@DateTime.Now.Year</strong> All rights reserved.<a href="http://beian.miit.gov.cn/">豫ICP备2020032332号</a>
</footer>
@Html.Partial("_ControlSidebar")

@section scripts{
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $("body").removeClass("layout-top-nav");
        })
    </script>
}  

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_Layout1.cshtml
@{
    Layout = "~/Views/Shared/_Root.cshtml";
}

@section styles{
    @RenderSection("styles", required: false)
}

@Html.Partial("_LeftMenu1")
<div class="content-wrapper">
    <div class="container-fluid">
        @RenderBody()
    </div>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        经开人民医院门诊部
    </div>
    <strong>Copyright &copy; 2014-@DateTime.Now.Year</strong> All rights reserved.<a href="http://beian.miit.gov.cn/">豫ICP备2020032332号</a>
</footer>
@Html.Partial("_ControlSidebar")

@section scripts{
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $("body").removeClass("layout-top-nav");
        })
    </script>
}

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_Layout2.cshtml
@{
    Layout = "~/Views/Shared/_Root.cshtml";
}

@section styles{
    @RenderSection("styles", required: false)
}

@Html.Partial("_LeftMenu2")
<div class="content-wrapper">
    <div class="container-fluid">
        @RenderBody()
    </div>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        经开人民医院门诊部
    </div>
    <strong>Copyright &copy; 2014-@DateTime.Now.Year</strong> All rights reserved.<a href="http://beian.miit.gov.cn/">豫ICP备2020032332号</a>
</footer>
@Html.Partial("_ControlSidebar")

@section scripts{
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $("body").removeClass("layout-top-nav");
        })
    </script>
}

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_LeftMenu.cshtml
@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@Url.Content("~/Content/touxiang.jpg")" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>谢灿软件工作室</p>
                <a href="#"><i class="fa fa-circle text-success"></i>我们一直都在！</a>
            </div>
        </div>
        <!-- search form -->
        <form action="@Url.Action("Index","Search",new { area=""})" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="请输入关键字" />
                <span class="input-group-btn">
                    <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header"> WAITING</li>
            <li class="active treeview">
                <a href="~/Areas/Admin/Views/patient/Index3.cshtml">
                    <i class="fa fa-dashboard"></i> <span>挂号</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="glyphicon glyphicon-erase"></i> <span>取药</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-green">new</small>
                    </span>
                </a>
            </li>
            <li class="treeview">
                <a href="@Url.Action("Index","prescipt")">
                    <i class="glyphicon glyphicon-qrcode"></i>
                    <span>付款</span>
                </a>
            </li>
            <li class="header">LABELS</li>
            <li><a href="@Url.Action("Index","Home")"><i class="fa fa-server text-red"></i> <span>服务器状态</span></a></li>
            <li><a href="@Url.Action("Add","Voice")"><i class="fa fa-server text-red"></i> <span>Voice状态</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_LeftMenu1.cshtml
@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@Url.Content("~/Content/touxiang.jpg")" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>经开人民医院门诊部</p>
                <a href="#"><i class="fa fa-circle text-success"></i>我们一直都在！</a>
            </div>
        </div>
        <!-- search form -->
        <form action="@Url.Action("Index","Search",new { area=""})" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="请输入关键字" />
                <span class="input-group-btn">
                    <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">working</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-bell-o"></i> <span>公告</span>
                    <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>开单</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","patient")">
                    <i class="glyphicon glyphicon-user"></i> <span>患者信息</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("address","Home")">
                    <i class="glyphicon glyphicon-map-marker"></i>
                    <span>患者来源</span>
                </a>
            </li>
            <li class="header">LABELS</li>
            <li><a href="@Url.Action("Index","Home")"><i class="fa fa-server text-red"></i> <span>服务器状态</span></a></li>
            <li><a href="@Url.Action("Add","Voice")"><i class="fa fa-server text-red"></i> <span>Voice状态</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_LeftMenu2.cshtml
@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@Url.Content("~/Content/touxiang.jpg")" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>经开人民医院门诊部</p>
                <a href="#"><i class="fa fa-circle text-success"></i>我们一直都在！</a>
            </div>
        </div>
        <!-- search form -->
        <form action="@Url.Action("Index","Search",new { area=""})" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="请输入关键字" />
                <span class="input-group-btn">
                    <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="glyphicon glyphicon-heart-empty"></i> <span>医生</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="glyphicon glyphicon-heart-empty"></i>
                    <span>护士</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("index2","patient")">
                    <i class="fa fa-th"></i> <span>病人</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>审批</span>
                    <small class="label pull-right"> </small>
                    <small class="label pull-right bg-red">3</small>
                    <small class="label pull-right bg-blue">17</small>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> 药材</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> 器械</a></li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("address1","Home")">
                    <i class="glyphicon glyphicon-map-marker"></i>
                    <span>患者来源</span>
                </a>
            </li>
            <li class="header">LABELS</li>
            <li><a href="@Url.Action("Index","Home")"><i class="fa fa-server text-red"></i> <span>服务器状态</span></a></li>
            <li><a href="@Url.Action("Add","Voice")"><i class="fa fa-server text-red"></i> <span>Voice状态</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

门诊管理系统/门诊管理系统/Areas/Admin/Views/Shared/_TopMenu.cshtml
@{
    ViewBag.Layout = null;
}

<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Index","Home",new { area=""})" class="logo"><b>经开人民医院门诊部</b></a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @Html.Partial("_MessageMenu")
                @Html.Partial("_NotificationMenu")
                @Html.Partial("_TaskMenu")
                @Html.Partial("_UserMenu")
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>